In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/English Premier League - Player Stats - 24:25/epl_player_stats_24_25.csv")

In [3]:
df.head()

,Player Name,Club,Nationality,Position,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,...,Fouls,Yellow Cards,Red Cards,Saves,Saves %,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
0,Ben White,Arsenal,England,DEF,17,1198,0,2,9,12,...,10,2,0,0,0%,0,0,0,0,0.0
1,Bukayo Saka,Arsenal,England,MID,25,1735,6,10,67,2,...,15,3,0,0,0%,0,0,0,0,0.0
2,David Raya,Arsenal,Spain,GKP,38,3420,0,0,0,0,...,1,3,0,86,72%,0,0,8,53,2.1
3,Declan Rice,Arsenal,England,MID,35,2833,4,7,48,18,...,21,5,1,0,0%,0,0,0,0,0.0
4,Ethan Nwaneri,Arsenal,England,MID,26,889,4,0,24,0,...,9,1,0,0,0%,0,0,0,0,0.0

In [ ]:
df.columns

Index(['Player Name', 'Club', 'Nationality', 'Position', 'Appearances',
       'Minutes', 'Goals', 'Assists', 'Shots', 'Shots On Target',
       'Conversion %', 'Big Chances Missed', 'Hit Woodwork', 'Offsides',
       'Touches', 'Passes', 'Successful Passes', 'Passes%', 'Crosses',
       'Successful Crosses', 'Crosses %', 'fThird Passes',
       'Successful fThird Passes', 'fThird Passes %', 'Through Balls',
       'Carries', 'Progressive Carries', 'Carries Ended with Goal',
       'Carries Ended with Assist', 'Carries Ended with Shot',
       'Carries Ended with Chance', 'Possession Won', 'Dispossessed',
       'Clean Sheets', 'Clearances', 'Interceptions', 'Blocks', 'Tackles',
       'Ground Duels', 'gDuels Won', 'gDuels %', 'Aerial Duels', 'aDuels Won',
       'aDuels %', 'Goals Conceded', 'xGoT Conceded', 'Own Goals', 'Fouls',
       'Yellow Cards', 'Red Cards', 'Saves', 'Saves %', 'Penalties Saved',
       'Clearances Off Line', 'Punches', 'High Claims', 'Goals Prevented'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 562 entries, 0 to 561
Data columns (total 57 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Player Name                562 non-null    str
 1   Club                       562 non-null    str
 2   Nationality                562 non-null    str
 3   Position                   562 non-null    str
 4   Appearances                562 non-null    int64
 5   Minutes                    562 non-null    int64
 6   Goals                      562 non-null    int64
 7   Assists                    562 non-null    int64
 8   Shots                      562 non-null    int64
 9   Shots On Target            562 non-null    int64
 10  Conversion %               562 non-null    str
 11  Big Chances Missed         562 non-null    int64
 12  Hit Woodwork               562 non-null    int64
 13  Offsides                   562 non-null    int64
 14  Touches                    562 non-null    int64
 15  Passes                     562 non-null    int64
 16  Successful Passes          562 non-null    int64
 17  Passes%                    562 non-null    str
 18  Crosses                    562 non-null    int64
 19  Successful Crosses         562 non-null    int64
 20  Crosses %                  562 non-null    str
 21  fThird Passes              562 non-null    int64
 22  Successful fThird Passes   562 non-null    int64
 23  fThird Passes %            562 non-null    str
 24  Through Balls              562 non-null    int64
 25  Carries                    562 non-null    int64
 26  Progressive Carries        562 non-null    int64
 27  Carries Ended with Goal    562 non-null    int64
 28  Carries Ended with Assist  562 non-null    int64
 29  Carries Ended with Shot    562 non-null    int64
 30  Carries Ended with Chance  562 non-null    int64
 31  Possession Won             562 non-null    int64
 32  Dispossessed               562 non-null    int64
 33  Clean Sheets               562 non-null    int64
 34  Clearances                 562 non-null    int64
 35  Interceptions              562 non-null    int64
 36  Blocks                     562 non-null    int64
 37  Tackles                    562 non-null    int64
 38  Ground Duels               562 non-null    int64
 39  gDuels Won                 562 non-null    int64
 40  gDuels %                   562 non-null    str
 41  Aerial Duels               562 non-null    int64
 42  aDuels Won                 562 non-null    int64
 43  aDuels %                   562 non-null    str
 44  Goals Conceded             562 non-null    int64
 45  xGoT Conceded              562 non-null    int64
 46  Own Goals                  562 non-null    int64
 47  Fouls                      562 non-null    int64
 48  Yellow Cards               562 non-null    int64
 49  Red Cards                  562 non-null    int64
 50  Saves                      562 non-null    int64
 51  Saves %                    562 non-null    str
 52  Penalties Saved            562 non-null    int64
 53  Clearances Off Line        562 non-null    int64
 54  Punches                    562 non-null    int64
 55  High Claims                562 non-null    int64
 56  Goals Prevented            562 non-null    float64
dtypes: float64(1), int64(45), str(11)
memory usage: 250.4 KB

In [6]:
df.describe()

,Appearances,Minutes,Goals,Assists,Shots,Shots On Target,Big Chances Missed,Hit Woodwork,Offsides,Touches,...,Own Goals,Fouls,Yellow Cards,Red Cards,Saves,Penalties Saved,Clearances Off Line,Punches,High Claims,Goals Prevented
count,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,...,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000
mean,20.581851,1336.208185,1.713523,1.145907,17.526690,5.514235,2.135231,0.496441,2.250890,857.033808,...,0.058719,14.295374,2.756228,0.092527,4.161922,0.024911,0.145907,0.467972,1.304270,0.068505
std,12.136239,1055.099340,3.310674,2.197891,22.342341,9.407054,3.732051,0.986986,4.085456,729.009027,...,0.277056,15.040111,2.750985,0.307913,18.616319,0.187160,0.473986,2.832182,6.230133,0.635313
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.200000
25%,10.000000,336.750000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,199.250000,...,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,22.000000,1156.000000,0.000000,0.000000,10.000000,1.000000,1.000000,0.000000,1.000000,700.500000,...,0.000000,10.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,32.000000,2229.250000,2.000000,2.000000,25.000000,7.000000,3.000000,1.000000,3.000000,1356.750000,...,0.000000,22.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,38.000000,3420.000000,29.000000,18.000000,130.000000,61.000000,27.000000,6.000000,28.000000,3347.000000,...,3.000000,73.000000,12.000000,2.000000,153.000000,2.000000,3.000000,28.000000,56.000000,6.000000

In [7]:
df.isnull().sum()

Player Name                  0
Club                         0
Nationality                  0
Position                     0
Appearances                  0
Minutes                      0
Goals                        0
Assists                      0
Shots                        0
Shots On Target              0
Conversion %                 0
Big Chances Missed           0
Hit Woodwork                 0
Offsides                     0
Touches                      0
Passes                       0
Successful Passes            0
Passes%                      0
Crosses                      0
Successful Crosses           0
Crosses %                    0
fThird Passes                0
Successful fThird Passes     0
fThird Passes %              0
Through Balls                0
Carries                      0
Progressive Carries          0
Carries Ended with Goal      0
Carries Ended with Assist    0
Carries Ended with Shot      0
Carries Ended with Chance    0
Possession Won               0
Dispossessed                 0
Clean Sheets                 0
Clearances                   0
Interceptions                0
Blocks                       0
Tackles                      0
Ground Duels                 0
gDuels Won                   0
gDuels %                     0
Aerial Duels                 0
aDuels Won                   0
aDuels %                     0
Goals Conceded               0
xGoT Conceded                0
Own Goals                    0
Fouls                        0
Yellow Cards                 0
Red Cards                    0
Saves                        0
Saves %                      0
Penalties Saved              0
Clearances Off Line          0
Punches                      0
High Claims                  0
Goals Prevented              0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.dtypes

Player Name                      str
Club                             str
Nationality                      str
Position                         str
Appearances                    int64
Minutes                        int64
Goals                          int64
Assists                        int64
Shots                          int64
Shots On Target                int64
Conversion %                 float64
Big Chances Missed             int64
Hit Woodwork                   int64
Offsides                       int64
Touches                        int64
Passes                         int64
Successful Passes              int64
Passes%                          str
Crosses                        int64
Successful Crosses             int64
Crosses %                        str
fThird Passes                  int64
Successful fThird Passes       int64
fThird Passes %                  str
Through Balls                  int64
Carries                        int64
Progressive Carries            int64
Carries Ended with Goal        int64
Carries Ended with Assist      int64
Carries Ended with Shot        int64
Carries Ended with Chance      int64
Possession Won                 int64
Dispossessed                   int64
Clean Sheets                   int64
Clearances                     int64
Interceptions                  int64
Blocks                         int64
Tackles                        int64
Ground Duels                   int64
gDuels Won                     int64
gDuels %                         str
Aerial Duels                   int64
aDuels Won                     int64
aDuels %                         str
Goals Conceded                 int64
xGoT Conceded                  int64
Own Goals                      int64
Fouls                          int64
Yellow Cards                   int64
Red Cards                      int64
Saves                          int64
Saves %                          str
Penalties Saved                int64
Clearances Off Line            int64
Punches                        int64
High Claims                    int64
Goals Prevented              float64
dtype: object

In [10]:
df.nunique()

Player Name                  562
Club                          21
Nationality                   64
Position                       4
Appearances                   38
Minutes                      482
Goals                         19
Assists                       14
Shots                         83
Shots On Target               43
Conversion %                  32
Big Chances Missed            23
Hit Woodwork                   7
Offsides                      23
Touches                      474
Passes                       267
Successful Passes            270
Passes%                       35
Crosses                       83
Successful Crosses            29
Crosses %                     43
fThird Passes                219
Successful fThird Passes     217
fThird Passes %               46
Through Balls                 23
Carries                      216
Progressive Carries          190
Carries Ended with Goal        8
Carries Ended with Assist      8
Carries Ended with Shot       36
Carries Ended with Chance     29
Possession Won               137
Dispossessed                  62
Clean Sheets                  15
Clearances                   115
Interceptions                 53
Blocks                        36
Tackles                       90
Ground Duels                 172
gDuels Won                   125
gDuels %                      46
Aerial Duels                 122
aDuels Won                    85
aDuels %                      61
Goals Conceded                23
xGoT Conceded                 23
Own Goals                      4
Fouls                         62
Yellow Cards                  13
Red Cards                      3
Saves                         37
Saves %                       14
Penalties Saved                3
Clearances Off Line            4
Punches                       14
High Claims                   28
Goals Prevented               21
dtype: int64

In [11]:
df["Conversion %"] = df["Conversion %"].str.rstrip('%').astype(float)

In [12]:
df["Conversion %"].head()

0    13.0
1    25.0
2     0.0
3    15.0
4     0.0
Name: Conversion %, dtype: float64

In [13]:
df["Conversion %"].dtypes

dtype('float64')

In [15]:
df.dtypes

Player Name                      str
Club                             str
Nationality                      str
Position                         str
Appearances                    int64
Minutes                        int64
Goals                          int64
Assists                        int64
Shots                          int64
Shots On Target                int64
Conversion %                 float64
Big Chances Missed             int64
Hit Woodwork                   int64
Offsides                       int64
Touches                        int64
Passes                         int64
Successful Passes              int64
Passes%                          str
Crosses                        int64
Successful Crosses             int64
Crosses %                        str
fThird Passes                  int64
Successful fThird Passes       int64
fThird Passes %                  str
Through Balls                  int64
Carries                        int64
Progressive Carries            int64
Carries Ended with Goal        int64
Carries Ended with Assist      int64
Carries Ended with Shot        int64
Carries Ended with Chance      int64
Possession Won                 int64
Dispossessed                   int64
Clean Sheets                   int64
Clearances                     int64
Interceptions                  int64
Blocks                         int64
Tackles                        int64
Ground Duels                   int64
gDuels Won                     int64
gDuels %                         str
Aerial Duels                   int64
aDuels Won                     int64
aDuels %                         str
Goals Conceded                 int64
xGoT Conceded                  int64
Own Goals                      int64
Fouls                          int64
Yellow Cards                   int64
Red Cards                      int64
Saves                          int64
Saves %                          str
Penalties Saved                int64
Clearances Off Line            int64
Punches                        int64
High Claims                    int64
Goals Prevented              float64
dtype: object

In [ ]:
percentage_cols = [
    "Passes%",
    "Crosses %",
    "fThird Passes %",
    "gDuels %",
    "aDuels %",
    "Saves %"
]

for col in percentage_cols:
    df[col] = df[col].str.rstrip('%').astype(float)

In [22]:
df[percentage_cols].dtypes

Passes%            float64
Crosses %          float64
fThird Passes %    float64
gDuels %           float64
aDuels %           float64
Saves %            float64
dtype: object

In [23]:
df.to_csv("../data/English Premier League - Player Stats - 24:25/epl_player_stats_24_25_cleaned.csv", index=False)